[package]
name = "asm-lexer"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"

[dev-dependencies]
insta = { version = "1.29.0", features = ["yaml"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
